# -*- coding: utf-8 -*-
"""Finetuning Job

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_1_VIq6Hm2S14uNENTcdjIkZwDXPAi7I
"""

# !pip install trl bitsandbytes -q

import os, gc, json, math, time, random, textwrap, warnings
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Optional

warnings.filterwarnings("ignore")

import torch
import numpy as np
import wandb
from datasets import load_dataset, Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    GenerationConfig,
    set_seed,
)
from peft import LoraConfig, get_peft_model, TaskType

from trl import SFTTrainer, SFTConfig

os.environ["PYTORCH_ALLOC_CONF"] = "expandable_segments:True"

@dataclass
class RunConfig:
    base_model: str              = "google/gemma-2-9b-it"
    hf_username: str             = "kunjcr2"
    repo_id: str                 = "gemma-2-9b-proof-lora"

    dataset_name: str            = "open-web-math/open-web-math"
    max_samples_train: int       = 120_000 #########
    max_samples_val: int         = 3_000 #########
    max_seq_length: int          = 1_536
    min_proof_tokens: int        = 80
    seed: int                    = 42

    lora_r: int                  = 32
    lora_alpha: int              = 64
    lora_dropout: float          = 0.05
    target_modules: List[str]    = field(default_factory=lambda: [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ])

    num_train_epochs: int        = 3 #########
    per_device_train_batch_size: int  = 4
    per_device_eval_batch_size: int   = 2
    gradient_accumulation_steps: int  = 8
    learning_rate: float         = 1.5e-4
    lr_scheduler_type: str       = "cosine"
    warmup_ratio: float          = 0.05
    weight_decay: float          = 0.01
    max_grad_norm: float         = 1.0
    bf16: bool                   = True
    tf32: bool                   = True
    gradient_checkpointing: bool = True

    logging_steps: int           = 10
    eval_steps: int              = 500
    save_steps: int              = 500
    save_total_limit: int        = 3
    output_dir: str              = "./lora-ckpts"
    run_name: str                = "gemma2-9b-lora"
    wandb_project: str           = "gemma-9b-lora"


CFG = RunConfig()
set_seed(CFG.seed)
DEVICE = "cuda" if torch.cuda.is_available() else "cpu"

SYSTEM = (
    "You are a formal mathematics assistant. "
    "When given a mathematical statement or theorem, produce a rigorous, "
    "step-by-step proof. Structure your proof with clearly labelled steps: "
    "Given, Definitions, Lemma (if needed), Proof, and QED."
)

def make_prompt(statement: str, proof: str) -> str:
    return (
        f"<bos><start_of_turn>user\n"
        f"{SYSTEM}\n\n"
        f"Prove the following:\n\n{statement.strip()}"
        f"<end_of_turn>\n"
        f"<start_of_turn>model\n"
        f"{proof.strip()}"
        f"<end_of_turn>"
    )

def make_prompt_only(statement: str) -> str:
    return (
        f"<bos><start_of_turn>user\n"
        f"{SYSTEM}\n\nProve the following:\n\n{statement.strip()}"
        f"<end_of_turn>\n<start_of_turn>model\n"
    )

RESPONSE_TEMPLATE = "<start_of_turn>model\n" # This to be replaced

PROOF_KEYWORDS  = ["Proof.", "Proof:", "\\begin{proof}", "We prove", "We show",
                   "By induction", "Suppose for contradiction", "QED",
                   "\\square", "\\blacksquare"]
THEOREM_KEYWORDS = ["Theorem", "Lemma", "Proposition", "Corollary", "Claim"]

def _looks_like_proof(text):
    return (any(k in text for k in THEOREM_KEYWORDS) and
            any(k in text for k in PROOF_KEYWORDS))

def _split(text):
    for marker in ["Proof.", "Proof:", "\\begin{proof}"]:
        idx = text.find(marker)
        if idx > 40:
            return text[:idx].strip(), text[idx:].strip()
    return None

def load_proof_dataset(tokenizer):
    print("\n[DATA] Streaming DS …")
    raw = load_dataset(CFG.dataset_name, split="train",
                       streaming=True)
    train_rows, val_rows = [], []
    n_seen = n_kept = 0

    for sample in raw:
        n_seen += 1
        text = sample.get("text", "")
        if not text or len(text) < 200 or not _looks_like_proof(text):
            continue
        result = _split(text)
        if result is None:
            continue
        statement, proof = result
        if len(tokenizer.encode(proof, add_special_tokens=False)) < CFG.min_proof_tokens:
            continue
        full = make_prompt(statement, proof)
        if len(tokenizer.encode(full, add_special_tokens=False)) > CFG.max_seq_length:
            continue

        # after every 33 training seq, we have 1 val seq
        row = {"prompt": make_prompt_only(statement), "completion": proof}
        if n_kept % 33 == 0 and len(val_rows) < CFG.max_samples_val:
            val_rows.append(row)
        elif len(train_rows) < CFG.max_samples_train:
            train_rows.append(row)
        n_kept += 1
        if n_kept % 5_000 == 0:
            print(f"  kept {n_kept:,} / seen {n_seen:,}")
        # if both full, we break
        if len(train_rows) >= CFG.max_samples_train and len(val_rows) >= CFG.max_samples_val:
            break

    print(f"\n[DATA] train: {len(train_rows):,}  val: {len(val_rows):,}")
    return DatasetDict({
        "train":      Dataset.from_list(train_rows),
        "validation": Dataset.from_list(val_rows),
    })

def load_base_model_and_tokenizer():
    print("\n[MODEL] Loading tokenizer …")
    tokenizer = AutoTokenizer.from_pretrained(CFG.base_model, use_fast=True, # use_fast uses RUST
                                               padding_side="right")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    print("[MODEL] Loading model in bf16 …")
    model = AutoModelForCausalLM.from_pretrained(
        CFG.base_model, torch_dtype=torch.bfloat16,
        device_map="auto", attn_implementation="eager",
    )
    model.config.use_cache = False
    print(f"[MODEL] Params: {model.num_parameters():,}")
    return model, tokenizer

def attach_lora(model):
    cfg = LoraConfig(r=CFG.lora_r, lora_alpha=CFG.lora_alpha,
                     lora_dropout=CFG.lora_dropout,
                     target_modules=CFG.target_modules,
                     bias="none", task_type=TaskType.CAUSAL_LM)
    model = get_peft_model(model, cfg)
    model.print_trainable_parameters()
    return model

EVAL_STATEMENTS = [
    "The square root of 2 is irrational.",
    "There are infinitely many prime numbers.",
    "For any integer n, n² + n is even.",
    "The sum of angles in any triangle is 180°.",
    "If p is prime and p | ab, then p | a or p | b.",
    "For all n ≥ 1, 1 + 2 + ... + n = n(n+1)/2.",
    "The product of two odd integers is odd.",
    "e^(iπ) + 1 = 0  (Euler's identity, sketch the derivation).",
]

GEN_CONFIG = GenerationConfig(max_new_tokens=512, temperature=0.3,
                               top_p=0.9, do_sample=True, repetition_penalty=1.1)

def run_eval(model, tokenizer, tag):
    model.eval()
    results = []
    print(f"\n{'═'*60}\n  EVAL [{tag}]\n{'═'*60}")
    for stmt in EVAL_STATEMENTS:
        prompt = (f"<bos><start_of_turn>user\n{SYSTEM}\n\n"
                  f"Prove the following:\n\n{stmt}<end_of_turn>\n"
                  f"<start_of_turn>model\n")
        inputs = tokenizer(prompt, return_tensors="pt",
                           truncation=True, max_length=CFG.max_seq_length).to(DEVICE)
        with torch.no_grad():
            out = model.generate(**inputs, generation_config=GEN_CONFIG)
        response = tokenizer.decode(out[0][inputs.input_ids.shape[-1]:],
                                    skip_special_tokens=True)
        results.append({"statement": stmt, "response": response, "tag": tag})
        print(f"\n── {stmt}\n{textwrap.fill(response, 88)}")
    model.train()
    wandb.log({f"qualitative_eval/{tag}": wandb.Table(
        columns=["statement","response","tag"],
        data=[[r["statement"],r["response"],r["tag"]] for r in results])})
    return results

def score_and_log(results, tag):
    def score(text):
        return {
            "has_given":    int("given" in text.lower() or "suppose" in text.lower()),
            "has_qed":      int("qed" in text.lower() or "□" in text or "∎" in text),
            "step_markers": sum(text.lower().count(w) for w in
                                ["therefore","thus","hence","it follows"]),
            "proof_kw":     int("proof" in text.lower()),
            "n_sentences":  text.count(". "),
        }
    all_s = [score(r["response"]) for r in results]
    agg = {k: np.mean([s[k] for s in all_s]) for k in all_s[0]}
    wandb.log({f"proof_quality/{tag}/{k}": v for k, v in agg.items()})
    print(f"[SCORES/{tag}] {json.dumps(agg, indent=2)}")
    return agg

def build_trainer(model, tokenizer, dataset):

    sft_cfg = SFTConfig(
        output_dir=CFG.output_dir,
        num_train_epochs=CFG.num_train_epochs,
        per_device_train_batch_size=CFG.per_device_train_batch_size,
        per_device_eval_batch_size=CFG.per_device_eval_batch_size,
        gradient_accumulation_steps=CFG.gradient_accumulation_steps,
        learning_rate=CFG.learning_rate,
        lr_scheduler_type=CFG.lr_scheduler_type,
        warmup_ratio=CFG.warmup_ratio,
        weight_decay=CFG.weight_decay,
        max_grad_norm=CFG.max_grad_norm,
        bf16=CFG.bf16,
        tf32=CFG.tf32,
        gradient_checkpointing=CFG.gradient_checkpointing,
        logging_steps=CFG.logging_steps,
        eval_strategy="steps",
        eval_steps=CFG.eval_steps,
        save_strategy="steps",
        save_steps=CFG.save_steps,
        save_total_limit=CFG.save_total_limit,
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="wandb",
        run_name=CFG.run_name,
        dataloader_num_workers=4,
        dataloader_pin_memory=True,
        optim="paged_adamw_32bit",
        group_by_length=True,
        seed=CFG.seed,
        completion_only_loss=True,

        max_length=CFG.max_seq_length,
        packing=False,
    )

    return SFTTrainer(
        model=model,
        args=sft_cfg,
        train_dataset=dataset["train"],
        eval_dataset=dataset["validation"],
    )

def push_to_hub(model, tokenizer):
    repo = f"{CFG.hf_username}/{CFG.repo_id}"
    print(f"\n[HUB] Pushing → {repo}")
    model.push_to_hub(repo, private=False)
    tokenizer.push_to_hub(repo, private=False)
    card = textwrap.dedent(f"""
    # {CFG.repo_id}
    LoRA adapter · **{CFG.base_model}** · formal math proof writing

    | | |
    |---|---|
    | Dataset | `{CFG.dataset_name}` |
    | LoRA r / α | {CFG.lora_r} / {CFG.lora_alpha} |
    | Epochs | {CFG.num_train_epochs} |
    | Effective batch | {CFG.per_device_train_batch_size * CFG.gradient_accumulation_steps} |
    | LR | {CFG.learning_rate} |

    ## Usage
    ```python
    from transformers import AutoTokenizer, AutoModelForCausalLM
    from peft import PeftModel
    import torch
    base  = AutoModelForCausalLM.from_pretrained("{CFG.base_model}",
                torch_dtype=torch.bfloat16, device_map="auto")
    model = PeftModel.from_pretrained(base, "{repo}")
    tok   = AutoTokenizer.from_pretrained("{repo}")
    prompt = ("<bos><start_of_turn>user\\nProve: sqrt(2) is irrational."
              "<end_of_turn>\\n<start_of_turn>model\\n")
    ids = tok(prompt, return_tensors="pt").to("cuda")
    print(tok.decode(model.generate(**ids, max_new_tokens=512)[0]))
    ```
    """).strip()
    (Path(CFG.output_dir) / "README.md").write_text(card)
    print("[HUB] Done.")

def main():
    assert torch.cuda.is_available(), "No GPU."
    gpu_mem = torch.cuda.get_device_properties(0).total_memory / 1e9
    print(f"[ENV] {torch.cuda.get_device_name(0)}  {gpu_mem:.1f} GB")
    assert gpu_mem >= 38, f"Need ≥40GB, got {gpu_mem:.1f}GB"

    if CFG.tf32:
        torch.backends.cuda.matmul.allow_tf32 = True
        torch.backends.cudnn.allow_tf32 = True

    wandb.init(project=CFG.wandb_project, name=CFG.run_name,
               config=CFG.__dict__, tags=["gemma-2","lora","math-proofs"])

    model, tokenizer = load_base_model_and_tokenizer()

    # before_results = run_eval(model, tokenizer, "before")
    # before_scores  = score_and_log(before_results, "before")

    model   = attach_lora(model)
    dataset = load_proof_dataset(tokenizer)
    trainer = build_trainer(model, tokenizer, dataset)

    print("\n[TRAIN] Starting …")
    t0 = time.time()
    trainer.train()
    elapsed = (time.time() - t0) / 3600
    print(f"[TRAIN] Done in {elapsed:.2f}h")
    wandb.log({"train/total_hours": elapsed})

    after_results = run_eval(model, tokenizer, "after")
    after_scores  = score_and_log(after_results, "after")
    # for k in before_scores:
    #     wandb.log({f"proof_quality/delta/{k}": after_scores[k] - before_scores[k]})

    trainer.save_model(CFG.output_dir)
    push_to_hub(model, tokenizer)
    wandb.finish()
    print("\n✓ Done.")

main()

