######################################################################################
# PPO in trl is experimental. This code has some serious issues. DONT USE IT BLINDLY.
######################################################################################

# -*- coding: utf-8 -*-
"""PPO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HLdyH6QdWLEk1Fo1VXbvCEYDMdFrfuBJ
"""

# !pip install -q trl

import torch
import numpy as np
import torch.nn.functional as F
from datasets import load_dataset, Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, AutoModelForCausalLM

from trl import SFTTrainer, SFTConfig
from trl.experimental.utils import create_reference_model
from trl.experimental.ppo import PPOTrainer, PPOConfig, AutoModelForCausalLMWithValueHead

from peft import LoraConfig, PeftModel

# ── Global settings ──────────────────────────────────────────────────────────
DEVICE     = "cuda" if torch.cuda.is_available() else "cpu"
BASE_ID    = "Qwen/Qwen2.5-0.5B-Instruct"   # small model with a chat template
RM_ID      = "OpenAssistant/reward-model-deberta-v3-large-v2"
MAXLEN_SFT = 1024
MAXLEN_RM  = 512

# ── Tokenizer ─────────────────────────────────────────────────────────────────
tok = AutoTokenizer.from_pretrained(BASE_ID, use_fast=True)
if tok.pad_token is None:          # DeBERTa uses eos as pad
    tok.pad_token = tok.eos_token

# =============================================================================
# 1) SFT — Supervised Fine-Tuning (policy initialisation)
# =============================================================================
print("=" * 60)
print("Stage 1 / 2 : SFT")
print("=" * 60)

# Load 6 000 instruction-response pairs
chat = load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft[:100]")

def sft_text(example):
    """
    ultrachat_200k schema:
        'messages' : list of {"role": "user"/"assistant", "content": "..."}
        'prompt'   : string (the final user turn, used separately in PPO)

    We feed the full 'messages' list directly into apply_chat_template —
    no manual field extraction needed and works for multi-turn conversations.
    """
    return {"text": tok.apply_chat_template(
        example["messages"],
        tokenize=False,
        add_generation_prompt=False,
    )}

chat = chat.map(sft_text, remove_columns=chat.column_names)

# Load base model with 4-bit quantisation + LoRA adapters
policy_sft = AutoModelForCausalLM.from_pretrained(
    BASE_ID, device_map="auto"
)
peft_cfg = LoraConfig(
    r=16, lora_alpha=32, lora_dropout=0.05, bias="none", task_type="CAUSAL_LM"
)

sft_cfg = SFTConfig(
    output_dir="ckpt_sft",
    dataset_text_field="text",         # preferred over deprecated formatting_func
    max_length=MAXLEN_SFT,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=16,
    num_train_epochs=1,
    learning_rate=5e-5,
    logging_steps=1,
    report_to=["wandb"],
)

sft_tr = SFTTrainer(
    model=policy_sft,
    train_dataset=chat,
    args=sft_cfg,
    peft_config=peft_cfg,
)

sft_tr.train()
sft_tr.model.save_pretrained("ckpt_sft")
tok.save_pretrained("ckpt_sft")
print("SFT checkpoint saved → ckpt_sft")

# =============================================================================
# 2) Load the Pre-built Reward Model (no training needed)
# =============================================================================
print("=" * 60)
print("Loading pre-built reward model :", RM_ID)
print("=" * 60)

# DeBERTa is small enough to run on CPU if no GPU is available
rm_device = DEVICE
rm_tok = AutoTokenizer.from_pretrained(RM_ID)
rm_model = AutoModelForSequenceClassification.from_pretrained(RM_ID).to(rm_device)
rm_model.eval()


@torch.no_grad()
def reward_score(prompt: str, response: str) -> float:
    """
    Score a single prompt-response pair with the pre-built reward model.

    The DeBERTa model expects the concatenation format:
        "Question: <prompt>\n\nAnswer: <response>"
    and returns a single scalar logit (higher is better).
    """
    text = f"Question: {prompt}\n\nAnswer: {response}"
    enc  = rm_tok(
        text,
        return_tensors="pt",
        truncation=True,
        max_length=MAXLEN_RM,
    ).to(rm_device)
    return float(rm_model(**enc).logits[0])

class WrappedRewardModel(torch.nn.Module):
    def __init__(self, policy_tok, rm_tok, rm_model, device):
        super().__init__()
        self.policy_tok = policy_tok
        self.rm_tok     = rm_tok
        self.rm         = rm_model
        self.device     = device
        self.config            = rm_model.config
        self.base_model_prefix = rm_model.base_model_prefix

    def forward(self, input_ids, attention_mask=None, **kwargs):
        # Decode on CPU regardless of where input_ids lives
        texts = self.policy_tok.batch_decode(
            input_ids.cpu(), skip_special_tokens=True
        )
        scores = []
        for text in texts:
            enc = self.rm_tok(
                text,
                return_tensors="pt",
                truncation=True,
                max_length=MAXLEN_RM,
                padding=True,
            ).to(self.device)          # explicitly send to rm's device
            with torch.no_grad():
                score = self.rm(**enc).logits[0, 0]
            scores.append(score.to(input_ids.device))  # return on same device as input
        return torch.stack(scores)

    def __getattr__(self, name):
        try:
            return super().__getattr__(name)
        except AttributeError:
            return getattr(self.rm, name)

import os
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
os.environ["TORCH_USE_CUDA_DSA"] = "1"

# =============================================================================
# 3) PPO — Policy Optimisation
# =============================================================================
print("=" * 60)
print("Stage 2 / 2 : PPO")
print("=" * 60)

# Load the SFT checkpoint with a value head attached (required for PPO)
base = AutoModelForCausalLM.from_pretrained(BASE_ID, device_map="auto")
policy = PeftModel.from_pretrained(base, "ckpt_sft").merge_and_unload()
ref_policy = create_reference_model(policy)
value_model = AutoModelForSequenceClassification.from_pretrained(
    BASE_ID, num_labels=1, device_map="auto"
)

ppo_cfg = PPOConfig(
    learning_rate=1e-5,
    batch_size=16,
    mini_batch_size=8,
    num_train_epochs=2,
    whiten_rewards=True,
    remove_unused_columns=False,
    gradient_checkpointing=False,  # ← prevents the wrapper attr error
)


# ── Build a HF Dataset of chat-formatted prompts ──────────────────────────────
raw_prompts = load_dataset("HuggingFaceH4/ultrachat_200k", split="train_sft[:100]")["prompt"]

ppo_dataset = Dataset.from_list([
    {"input_ids": tok.apply_chat_template(
        [{"role": "user", "content": p}],
        tokenize=True,
        add_generation_prompt=True,
        return_dict=False
    )}
    for p in raw_prompts
])
wrapped_rm = WrappedRewardModel(tok, rm_tok, rm_model, rm_device)

ppo_tr = PPOTrainer(
    args=ppo_cfg,
    processing_class=tok,
    model=policy,
    ref_model=ref_policy,
    reward_model=wrapped_rm,
    value_model=value_model,
    train_dataset=ppo_dataset
)

ppo_tr.train() # requires JUST input ids

# ── Save final aligned policy ─────────────────────────────────────────────────
ppo_tr.model.save_pretrained("ckpt_ppo")
tok.save_pretrained("ckpt_ppo")
print("Saved aligned policy → ckpt_ppo")

